export const WINDOW_FLOATING_FOCUS_LAYER_START = 2_000;
export const WINDOW_FLOATING_FOCUS_LAYER_END = 9_999;
export const WINDOW_TOP_DOCKED_CHROME_LAYER = 10_000;
export const WINDOW_FULLSCREEN_PRESENTATION_LAYER = 11_000;
